created the Login, Registration, Verification, Forgot, and dashboard …
Slvzzzy/DashboardFormAuth pull request #1
Opened 2023-10-23 16:42 UTC by Slvzzzy

…pages. Added a routing module, an authentication service and a guard system. Made a connection to the Firebase database

2023-10-27 10:54 UTC, colorizeforever requested changes

2023-10-27 10:54 UTC, colorizeforever commented on package.json
>      "rxjs": "~7.8.0",
fasasf

2023-10-27 10:54 UTC, colorizeforever commented on src/app/components/main-page/main-page.component.html
> +              <a (click)="authService.signOut()">
fas

2023-11-02 10:10 UTC, colorizeforever requested changes

2023-11-02 10:10 UTC, colorizeforever commented on src/app/components/forgot-password/forgot-password.component.ts
> +    //this.authService.(this.registerForm.get('password').value)
//this.authService.(тут метод должен быть какой-то) куда ты прокидываешь значения пароля. откуда берется значение пароля?

2023-11-02 18:49 UTC, emasloborodov requested changes

2023-11-02 18:49 UTC, emasloborodov commented on src/app/app-routing.module.ts
> +  { path: 'main-page', component: MainPageComponent, canLoad: [AuthGuard], canMatch: [AuthGuard] },
canMatch и canLoad тут делают одну и ту же работу 
Убери один из них

2023-11-02 18:49 UTC, emasloborodov commented on src/app/app-routing.module.ts
> +  { path: 'main-page', component: MainPageComponent, canLoad: [AuthGuard], canMatch: [AuthGuard] },
canLoad - можно ли загружать модуль
canActivate - можно ли переходить по роуту
canMatch - делает и то другое

2023-11-02 18:49 UTC, emasloborodov commented on src/app/app-routing.module.ts
> +  { path: 'main-page', component: MainPageComponent, canLoad: [AuthGuard], canMatch: [AuthGuard] },
Еще не многие проекты переехали на новый ангуляр так что стоит помнить их все
Но если будешь работать с 14 и выше приоритетнее использовать **canMatch**

2023-11-02 18:49 UTC, emasloborodov commented on src/app/app-routing.module.ts
> +  { path: 'main-page', component: MainPageComponent, canLoad: [AuthGuard], canMatch: [AuthGuard] },
Они кстати с недавних пор все deprecated, так что скоро придется учить canMatchFn, и остальные can_Fn, как их функциональные заменители

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-in/sign-in.component.ts
> +    console.log('UserInfo:', this.form.getRawValue())
Логи не должны лететь в МР, если в них нет другого смысла, кроме как сливать инфу о пользователе
Можно выводить логи запросов, ошибок и системные оповещения
НО такое лучше согласовывать

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-in/sign-in.component.ts
> +    console.log('form', this.form.get(fieldName))
То же самое

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-in/sign-in.component.html
> +            {{getAuthErrorMessage('password')}}
Использование функций в темплейте не рекомендуется
Можно использовать для какого геттера с МИНИМОМ реализации
Зайди в этот метод, закинь туда лог, и посмотри сколько раз вызывается эта функция если пользователь просто водит мышкой по компоненту

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-in/sign-in.component.html
> +            {{getAuthErrorMessage('email')}}
К вопросу о функциях в темлейте

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-in/sign-in.component.html
> +            {{getAuthErrorMessage('password')}}
Можно вешать на определенные пользовательские действия, такие как клик
Но каждая переписовка будет тригерить вызов метода, если оставить его болтаться просто в темплейте

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-up/sign-up.component.html
> +            {{getAuthErrorMessage('email')}}
К вопросу о функциях в темлейте

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-up/sign-up.component.html
> +            {{getAuthErrorMessage('password')}}
К вопросу о функциях в темлейте

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-in/sign-in.component.ts
> +    console.log('UserInfo:', this.form.getRawValue())
Это просто памятка
При обучении - ладно 
Но при работе старайся не оставлять логов когда будешь готовить МР

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-up/sign-up.component.html
> +            class="btn btnPrimary"
btnPrimary - выбивается из общего стиля 
Следует придерживаться или camelCase или snake_case
Что так же актуально и в объектах, функциях и переменных
Тут замени на btn-primary

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-up/sign-up.component.html
> +        <div class="redirectToLogin">
redirect-to-login

2023-11-02 18:49 UTC, emasloborodov commented on src/app/shared/guard/auth.guard.ts
> +import {Observable, } from 'rxjs';
Запятая почему то попала?

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/user-profile/user-profile.component.ts
> +  getUser() {
Можно в геттер переделать

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-in/sign-in.component.html
> +      <div class="redirectToLogin">
redirect-to-login

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/sign-in/sign-in.component.html
> +            class="btn btnPrimary"
btn-primary

2023-11-02 18:49 UTC, emasloborodov commented on src/app/components/main-page/main-page.component.ts
>    public readonly navBarDate = navBarDate;
Объявлять переменные следует до конструктора

2023-11-02 18:59 UTC, emasloborodov commented on src/app/app-routing.module.ts
> +  { path: 'main-page', component: MainPageComponent, canLoad: [AuthGuard], canMatch: [AuthGuard] },
И я увидел чуть дальше использование CanMatchFn, но там немного другая идея закладывалась в него 
Тут какая то мешанина получилась 
Или используй обычный CanMatch 
Или можешь чекнуть здесь с vpn
https://medium.com/ngconf/functional-route-guards-in-angular-8829f0e4ca5c

2023-11-02 20:26 UTC, colorizeforever commented on src/app/components/sign-up/sign-up.component.html
> +            formControlName="login"
вот тут при регистрации и кроется ошибка, formControlName=login, которого у тебя нет, заменишь на email - все будет окей

2023-11-02 20:27 UTC, colorizeforever commented on src/app/components/sign-up/sign-up.component.html
> +            {{getAuthErrorMessage('email')}}
@Slvzzzy на самом деле он прав, лучше тогда переписать на стандартную обработку ошибок(примеры есть в инете) https://angular.io/guide/form-validation

2023-11-02 20:29 UTC, colorizeforever commented on src/app/components/forgot-password/forgot-password.component.ts
> +
у тебя тут нет формы, значение с  которой будет браться и отправляться значение. напомню, тебе нужно отправлять будет email.

2023-11-02 20:32 UTC, colorizeforever commented on src/app/components/forgot-password/forgot-password.component.html
> +        <input type="submit" class="btn btnPrimary" value="Обновить пароль" (click)="forgotPassword()">
поменяй <input type=submit> на button.

2023-11-02 20:33 UTC, colorizeforever commented on src/app/components/forgot-password/forgot-password.component.html
> +        <input type="email" class="form-control" placeholder="Почта" #passwordResetEmail required>
вот с этого инпута должны данные браться. в компоненте создаешь форму, с контролом email, и форм контрол сюда навешиваешь

2023-11-07 19:57 UTC, emasloborodov requested changes

2023-11-07 19:57 UTC, emasloborodov commented on src/app/components/verify-email/verify-email.component.ts
> +    return  this.authService.userData
Тоже можно в геттер

2023-11-07 19:57 UTC, emasloborodov commented on src/app/components/sign-up/sign-up.component.ts
> +    return this.registerForm.get(controlName) as FormControl
Это кажется мне абсолютно лишним
Почему нельзя просто использовать registerForm.get('email').invalid или registerForm.controls.email.invalid в темплейте например?

2023-11-07 19:57 UTC, emasloborodov commented on src/styles.css
> +  align-content: start;
Ругается компилятор 
Поменяй на flex-start
<img width="816" alt="image" src="https://github.com/Slvzzzy/DashboardFormAuth/assets/147430346/151b7515-d6d1-4684-9298-9e818ba73ecd">

2023-11-07 19:57 UTC, emasloborodov commented on src/app/components/sign-up/sign-up.component.ts
> +    return this.registerForm.get(controlName) as FormControl
Я понимаю, что раньше формы плохо типизировались, но в новых версиях такой проблемы нет 
Это хорошее знание, в любом случае, но конкретно в этой версии - лишнее

2023-11-08 14:31 UTC, colorizeforever commented on src/app/components/verify-email/verify-email.component.ts
> +    return  this.authService.userData
по-хорошему бы типизировать

2023-11-08 19:08 UTC, colorizeforever commented on src/app/components/verify-email/verify-email.component.ts
> +  get getUser(): User {
геттер должен быть таким **get user** , а не get getUser

2023-11-09 10:24 UTC, merged